name: darpule
description: Lightweight, Robust Immutable Tuple Implementation.
version: 0.2.0
author: Ray King <taipan.king@gmail.com>
homepage: http://rayk.github.io/darpule

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  quiver_collection: "^1.0.0-dev.1"
  quiver_hashcode: "^1.0.0-dev.1"
  quiver_optional: "^1.0.0-dev.1"

dev_dependencies:
  changelog: "^1.3.6"
  coverage: "^0.7.2"
  dart_dev: "^1.0.3"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: '>=0.12.0 <0.13.0'

